# ビルドステージ
FROM node:20 AS builder

WORKDIR /app

COPY package.json .
RUN npm install

COPY . .
RUN npm run build

# 本番ステージ
FROM nginx:alpine

# ビルドしたファイルをNginxにコピー
COPY --from=builder /app/dist /usr/share/nginx/html

# Nginx設定ファイルをコピー
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

